on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Safe directory
        run: git config --global --add safe.directory '*'
      - name: Check formatting
        run: crystal tool format --check
      - name: Install tree-sitter
        run: apt update && apt install libtree-sitter-dev -y
      - name: Build
        run: make
      - name: Run tests
        run: crystal spec --order=random
      
